import os
import shutil
import asyncio
import json
import re
from typing import List, Optional, Dict, Any

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    WebSocket,
    WebSocketDisconnect,
    File,
    UploadFile,
)
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from openai import AsyncOpenAI

from app.database import get_db
from app.models import (
    Project,
    Deployment,
    User,
    Document,
    ArchitectureVersion,
    Review,
    ReviewFinding,
    Requirement,
)
from app.schemas import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectsListResponse,
    DeploymentCreate,
    FindingUpdate,
)
from app.middleware.auth_middleware import get_current_user
from app.websocket import manager
from app.config import settings


router = APIRouter(prefix="/projects", tags=["projects"])


os.makedirs(settings.UPLOAD_DIR, exist_ok=True)


async def extract_text_from_file(file_path: str) -> str:
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    except Exception as e:
        return f"Error reading document text: {str(e)}"


# ============================================================
# AI ARCHITECTURE MODIFICATION HELPERS
# ============================================================

class ArchitectureModifyRequest(BaseModel):
    instruction: str


def _get_architecture_llm_client(provider: str):
    """
    Create an OpenAI-compatible client for Groq or Gemini.

    This uses the same environment variable names as chat.py:
      GROQ_API_KEYS
      GROQ_BASE_URL
      GROQ_MODEL
      GEMINI_API_KEYS
      GEMINI_BASE_URL
      GEMINI_MODEL
    """
    provider = provider.lower().strip()

    if provider == "groq":
        api_key = os.getenv("GROQ_API_KEYS", "").split(",")[0].strip()

        if not api_key:
            raise RuntimeError("GROQ_API_KEYS is missing")

        return (
            AsyncOpenAI(
                api_key=api_key,
                base_url=os.getenv(
                    "GROQ_BASE_URL",
                    "https://api.groq.com/openai/v1",
                ),
            ),
            os.getenv(
                "GROQ_MODEL",
                "llama-3.3-70b-versatile",
            ),
        )

    if provider == "gemini":
        api_key = os.getenv("GEMINI_API_KEYS", "").split(",")[0].strip()

        if not api_key:
            raise RuntimeError("GEMINI_API_KEYS is missing")

        return (
            AsyncOpenAI(
                api_key=api_key,
                base_url=os.getenv(
                    "GEMINI_BASE_URL",
                    "https://generativelanguage.googleapis.com/v1beta/openai",
                ),
            ),
            os.getenv(
                "GEMINI_MODEL",
                "gemini-2.5-flash",
            ),
        )

    raise RuntimeError(f"Unsupported LLM provider: {provider}")


def _extract_json_object(text: str) -> Dict[str, Any]:
    """
    Parse the JSON returned by the LLM.

    It also tolerates accidental ```json ... ``` wrappers even though
    the prompt explicitly tells the model not to use Markdown fences.
    """
    if not text or not text.strip():
        raise ValueError("AI returned an empty response")

    cleaned = text.strip()

    cleaned = re.sub(
        r"^```(?:json)?\s*",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        start = cleaned.find("{")
        end = cleaned.rfind("}")

        if start == -1 or end == -1 or end <= start:
            raise ValueError("AI did not return valid JSON")

        parsed = json.loads(cleaned[start:end + 1])

    if not isinstance(parsed, dict):
        raise ValueError("AI response must be a JSON object")

    return parsed


def _normalise_architecture(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Keep the architecture shape predictable for the frontend while
    preserving extra fields generated by the agent pipeline.
    """
    if not isinstance(data, dict):
        raise ValueError("architectureData must be a JSON object")

    data.setdefault("components", [])
    data.setdefault("database_schema", [])
    data.setdefault("apis", [])
    data.setdefault("cloud_mappings", [])
    data.setdefault("costs", {})

    if not isinstance(data["components"], list):
        data["components"] = []

    if not isinstance(data["database_schema"], list):
        data["database_schema"] = []

    if not isinstance(data["apis"], list):
        data["apis"] = []

    if not isinstance(data["cloud_mappings"], list):
        data["cloud_mappings"] = []

    if not isinstance(data["costs"], dict):
        data["costs"] = {}

    return data


async def _call_architecture_llm(
    provider: str,
    system_prompt: str,
    user_prompt: str,
) -> str:
    client, model = _get_architecture_llm_client(provider)

    response = await client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
        temperature=0.1,
        max_tokens=6000,
    )

    if (
        not response.choices
        or not response.choices[0].message.content
    ):
        raise RuntimeError("LLM returned an empty response")

    return response.choices[0].message.content


@router.get("", response_model=ProjectsListResponse)
async def get_projects(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(Project.ownerId == current_user.id)
    )
    projects = result.scalars().all()
    count = len(projects)
    return {"count": count, "projects": projects}


@router.post("", response_model=ProjectResponse, status_code=201)
async def create_project(
    project: ProjectCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    new_project = Project(
        name=project.name,
        description=project.description,
        ownerId=current_user.id,
    )
    db.add(new_project)
    await db.commit()
    await db.refresh(new_project)
    return new_project


@router.get("/{id}", response_model=ProjectResponse)
async def get_project(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )
    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    return project


@router.put("/{id}", response_model=ProjectResponse)
async def update_project(
    id: str,
    project_update: ProjectUpdate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )
    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    if project_update.description is not None:
        project.description = project_update.description

    await db.commit()
    await db.refresh(project)
    return project


@router.delete("/{id}", status_code=204)
async def delete_project(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )
    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    await db.delete(project)
    await db.commit()
    return None


# ============================================================
# DOCUMENT UPLOAD
# ============================================================

@router.post("/{id}/documents", status_code=201)
async def upload_document(
    id: str,
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    # Verify project ownership
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )
    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    # Save uploaded file
    file_path = os.path.join(
        settings.UPLOAD_DIR,
        f"{id}_{file.filename}",
    )

    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    # Get file stats
    file_size = os.path.getsize(file_path)
    extracted_text = await extract_text_from_file(file_path)

    # Save to database
    new_doc = Document(
        projectId=id,
        name=file.filename,
        filePath=file_path,
        fileSize=file_size,
        extractedText=extracted_text,
    )

    db.add(new_doc)
    await db.commit()
    await db.refresh(new_doc)

    return {
        "id": new_doc.id,
        "name": new_doc.name,
        "fileSize": new_doc.fileSize,
        "message": "Document uploaded and parsed successfully!",
    }


# ============================================================
# RETRIEVE AGENT OUTPUTS
# ============================================================

@router.get("/{id}/architecture")
async def get_logical_architecture(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_version = result.scalars().first()

    if not latest_version or not latest_version.architectureData:
        raise HTTPException(
            status_code=404,
            detail="No architecture design generated yet.",
        )

    return latest_version.architectureData.get("components", [])


@router.get("/{id}/architecture/database")
async def get_database_schema(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_version = result.scalars().first()

    if not latest_version or not latest_version.architectureData:
        raise HTTPException(
            status_code=404,
            detail="No database schema generated yet.",
        )

    return latest_version.architectureData.get("database_schema", [])


@router.get("/{id}/architecture/apis")
async def get_api_specifications(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_version = result.scalars().first()

    if not latest_version or not latest_version.architectureData:
        raise HTTPException(
            status_code=404,
            detail="No API specifications generated yet.",
        )

    return latest_version.architectureData.get("apis", [])


@router.get("/{id}/cloud-mapping")
async def get_cloud_mappings(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_version = result.scalars().first()

    if not latest_version or not latest_version.architectureData:
        raise HTTPException(
            status_code=404,
            detail="No cloud service mapping generated yet.",
        )

    return {
        "mappings": latest_version.architectureData.get(
            "cloud_mappings",
            [],
        ),
        "costs": latest_version.architectureData.get(
            "costs",
            {},
        ),
    }


@router.get("/{id}/terraform")
async def get_terraform_code(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_version = result.scalars().first()

    if not latest_version or not latest_version.terraformCode:
        raise HTTPException(
            status_code=404,
            detail="No Terraform code compiled yet.",
        )

    return {
        "version": latest_version.versionNumber,
        "terraformCode": latest_version.terraformCode,
    }


@router.get("/{id}/reviews")
async def get_reviews_findings(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    review_res = await db.execute(
        select(Review)
        .filter(Review.projectId == id)
        .order_by(Review.createdAt.desc())
    )

    latest_review = review_res.scalars().first()

    if not latest_review:
        raise HTTPException(
            status_code=404,
            detail="No architecture audit grading performed yet.",
        )

    findings_res = await db.execute(
        select(ReviewFinding).filter(
            ReviewFinding.reviewId == latest_review.id
        )
    )

    findings = findings_res.scalars().all()

    return {
        "score": latest_review.score,
        "status": latest_review.status,
        "findings": findings,
    }


@router.get("/{id}/versions")
async def get_all_versions(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    versions = result.scalars().all()

    return [
        {
            "id": v.id,
            "versionNumber": v.versionNumber,
            "createdAt": v.createdAt,
        }
        for v in versions
    ]


# ============================================================
# LIVE SPECIFICATION EDITING & RETRIEVAL
# ============================================================

class DocumentationUpdate(BaseModel):
    markdown: str


class ArchitectureUpdatePayload(BaseModel):
    architectureData: Dict[str, Any]
    terraformCode: Optional[str] = None


@router.get("/{id}/documentation")
async def get_project_documentation(
    id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )

    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    docs_path = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "../../../docs/architecture_docs.md",
        )
    )

    if not os.path.exists(docs_path):
        return {
            "markdown": (
                "# Executive Architecture Specifications\n\n"
                "No documentation compiled yet. "
                "Start the pipeline to generate it!"
            )
        }

    try:
        with open(docs_path, "r", encoding="utf-8") as f:
            return {"markdown": f.read()}
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to read documentation: {str(e)}",
        )


@router.post("/{id}/documentation")
async def update_project_documentation(
    id: str,
    payload: DocumentationUpdate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )

    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    docs_path = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "../../../docs/architecture_docs.md",
        )
    )

    os.makedirs(
        os.path.dirname(docs_path),
        exist_ok=True,
    )

    try:
        with open(docs_path, "w", encoding="utf-8") as f:
            f.write(payload.markdown)

        return {
            "status": "success",
            "message": "Documentation saved successfully!",
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to write documentation: {str(e)}",
        )


# ============================================================
# NEW: AI ARCHITECTURE MODIFICATION ENDPOINT
# ============================================================

@router.post("/{id}/architecture/modify")
async def modify_project_architecture_with_ai(
    id: str,
    payload: ArchitectureModifyRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Convert a natural-language architecture command into a real,
    persisted architectureData modification.

    Examples:
      - Add Redis cache between API Server and Database
      - Add AWS S3 bucket for uploaded files
      - Add GET /api/v1/analytics endpoint
      - Rename table users to accounts
      - Remove Message Queue
      - Add NotificationService
    """
    instruction = payload.instruction.strip()

    if not instruction:
        raise HTTPException(
            status_code=400,
            detail="Modification instruction cannot be empty.",
        )

    # Verify ownership.
    project_result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )

    project = project_result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    # Load latest architecture.
    version_result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_version = version_result.scalars().first()

    if (
        not latest_version
        or not latest_version.architectureData
    ):
        raise HTTPException(
            status_code=404,
            detail="No architecture has been generated yet.",
        )

    try:
        if isinstance(latest_version.architectureData, dict):
            # Deep-copy through JSON so we never accidentally mutate
            # SQLAlchemy's existing JSON object before validation.
            current_architecture = json.loads(
                json.dumps(latest_version.architectureData)
            )
        else:
            current_architecture = json.loads(
                latest_version.architectureData
            )

        current_architecture = _normalise_architecture(
            current_architecture
        )
    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Current architecture data is invalid: {str(exc)}",
        )

    system_prompt = """
You are an AI software architecture modification engine.

Your task is to MODIFY the supplied architecture JSON according to the
user's instruction. Do not merely explain what the user could do.

Return ONLY valid JSON. Do not return Markdown and do not wrap the
response in ```json fences.

Return exactly this outer structure:

{
  "message": "Short description of what changed",
  "architectureData": {
    "...": "the COMPLETE modified architecture"
  }
}

Rules:

1. Preserve every unrelated part of the existing architecture.
2. architectureData must contain the COMPLETE architecture, not only
   the changed item.
3. Preserve unknown top-level fields. Do not discard fields simply
   because they are not listed in this prompt.
4. Keep components, database_schema, apis, cloud_mappings, costs and
   documentation when they already exist.
5. Never delete an unrelated component, API, table, mapping or field.

COMPONENTS
- When adding a component, follow the shape already used by existing
  components whenever possible.
- A new component should normally have id, name, type and description.
- Use a stable unique string id.
- Suitable types include Microservice, Cache, Object Storage, Database,
  Queue, API Server, Load Balancer, Authentication Service, Worker,
  Gateway and External Service.
- If the user asks for Redis, create a Redis/Cache component.
- If the user asks for AWS S3, create an AWS S3/Object Storage component.
- If the user asks for a named service, preserve that service name.

APIS
- API entries should preserve the existing API object shape.
- At minimum a newly added API should contain:
  method, path, description
- Common methods are GET, POST, PUT, PATCH and DELETE.
- Do not create a duplicate with the same method and path.

DATABASE
- Preserve the existing table and column shapes.
- When renaming a table, preserve its columns and other properties.
- Do not remove unrelated tables.
- When adding a table, use the existing column conventions where possible.

CLOUD MAPPINGS
- If the architecture already has cloud_mappings and the user explicitly
  adds an AWS/cloud resource, add an appropriate mapping when useful.
- Preserve all existing mappings.

CONNECTIONS
- If architectureData already contains a connections array, preserve it
  and update it when the instruction clearly describes a relationship.
- A connection should follow the existing connection shape. If the
  existing shape is { "from": "...", "to": "..." }, continue using it.
- Do not replace an existing connection representation with a new schema.

REMOVE
- If the user explicitly asks to remove an element, remove only that
  requested element and directly related connections.

RENAME
- Preserve all properties and change only the requested name/identifier
  unless another change is necessary to keep references consistent.

The message must be concise, for example:
"Added Redis Cache between API Server and Database."
"""

    user_prompt = (
        "CURRENT ARCHITECTURE:\n\n"
        + json.dumps(
            current_architecture,
            indent=2,
            ensure_ascii=False,
        )
        + "\n\nUSER MODIFICATION:\n\n"
        + instruction
        + "\n\nReturn the required JSON object only."
    )

    provider = os.getenv(
        "LLM_PROVIDER",
        "groq",
    ).lower().strip()

    raw_response = None

    try:
        raw_response = await _call_architecture_llm(
            provider,
            system_prompt,
            user_prompt,
        )
    except Exception as primary_error:
        print(
            "[ARCH MODIFY] Primary provider failed:",
            repr(primary_error),
        )

        # Same fallback strategy used by the chat route.
        if provider == "groq":
            try:
                raw_response = await _call_architecture_llm(
                    "gemini",
                    system_prompt,
                    user_prompt,
                )
            except Exception as fallback_error:
                print(
                    "[ARCH MODIFY] Gemini fallback failed:",
                    repr(fallback_error),
                )
                raise HTTPException(
                    status_code=503,
                    detail=(
                        "AI architecture modification service "
                        "is currently unavailable."
                    ),
                )
        else:
            raise HTTPException(
                status_code=503,
                detail=(
                    "AI architecture modification service "
                    "is currently unavailable."
                ),
            )

    try:
        parsed = _extract_json_object(raw_response)

        if "architectureData" not in parsed:
            raise ValueError(
                "architectureData missing from AI response"
            )

        modified_architecture = _normalise_architecture(
            parsed["architectureData"]
        )

        message = str(
            parsed.get(
                "message",
                "Architecture updated successfully.",
            )
        ).strip()

        if not message:
            message = "Architecture updated successfully."

    except Exception as parse_error:
        print(
            "[ARCH MODIFY] Invalid LLM response:",
            raw_response,
        )
        print(
            "[ARCH MODIFY] Parse error:",
            repr(parse_error),
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "AI returned an invalid architecture modification."
            ),
        )

    # Persist immediately. The frontend can therefore redraw from the
    # returned data without requiring a second Save click.
    latest_version.architectureData = modified_architecture

    try:
        await db.commit()
        await db.refresh(latest_version)
    except Exception as db_error:
        await db.rollback()

        print(
            "[ARCH MODIFY] Database save failed:",
            repr(db_error),
        )

        raise HTTPException(
            status_code=500,
            detail="Failed to save modified architecture.",
        )

    return {
        "status": "success",
        "message": message,
        "architectureData": modified_architecture,
        "versionNumber": latest_version.versionNumber,
    }


@router.put("/{id}/architecture")
async def update_project_architecture(
    id: str,
    payload: ArchitectureUpdatePayload,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )

    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    # Fetch latest version
    ver_result = await db.execute(
        select(ArchitectureVersion)
        .filter(ArchitectureVersion.projectId == id)
        .order_by(ArchitectureVersion.versionNumber.desc())
    )

    latest_ver = ver_result.scalars().first()

    if not latest_ver:
        raise HTTPException(
            status_code=404,
            detail="No architecture versions found",
        )

    latest_ver.architectureData = payload.architectureData

    if payload.terraformCode is not None:
        latest_ver.terraformCode = payload.terraformCode

    await db.commit()

    return {
        "status": "success",
        "message": "Architecture updated successfully!",
    }


# ============================================================
# DEPLOYMENT / WEBSOCKET
# ============================================================

@router.post("/{id}/deploy")
async def deploy_project(
    id: str,
    deployment_data: DeploymentCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).filter(
            Project.id == id,
            Project.ownerId == current_user.id,
        )
    )

    project = result.scalars().first()

    if not project:
        raise HTTPException(
            status_code=404,
            detail="Project not found",
        )

    new_deployment = Deployment(
        projectId=id,
        environment=deployment_data.environment,
        status="pending",
    )

    db.add(new_deployment)
    await db.commit()
    await db.refresh(new_deployment)

    # Broadcast deployment trigger
    asyncio.create_task(
        mock_deployment_task(
            id,
            new_deployment.id,
        )
    )

    return {
        "status": "success",
        "deploymentId": new_deployment.id,
    }


async def mock_deployment_task(
    project_id: str,
    deployment_id: str,
):
    await asyncio.sleep(1)

    await manager.broadcast(
        project_id,
        {
            "type": "deployment_update",
            "data": {
                "deploymentId": deployment_id,
                "status": "in_progress",
                "log": "Provisioning resources...",
            },
        },
    )

    await asyncio.sleep(2)

    await manager.broadcast(
        project_id,
        {
            "type": "deployment_update",
            "data": {
                "deploymentId": deployment_id,
                "status": "completed",
                "log": "Deployment successful.",
            },
        },
    )


@router.put("/{id}/findings/{findingId}")
async def update_finding(
    id: str,
    findingId: str,
    finding_update: FindingUpdate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    return {
        "id": findingId,
        "reviewId": "mock_review_id",
        "ruleId": "SEC-001",
        "severity": "high",
        "description": "Mock finding",
        "status": finding_update.status,
        "recommendation": "Mock recommendation",
        "createdAt": "2023-01-01T00:00:00Z",
        "updatedAt": "2023-01-01T00:00:00Z",
    }


@router.websocket("/{id}/ws")
async def websocket_endpoint(
    websocket: WebSocket,
    id: str,
):
    await manager.connect(
        websocket,
        id,
    )

    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(
            websocket,
            id,
        )
